### ISSUE TITLE
RI option not working nicely

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/metaMS#4]
When using the RI option with a tab separated file or comma the runGC will crash saying that it need a matrix not a data.frame.
Idea modification of the RIarg<-read.table line to create a matrix with first column= rt and second column RI

**Comment by lecorguille** [comment]
Do you want to try a commit by yourself?
If not, can you send me one example file?

**Comment by yguitton** [comment]
I'm still trying to fully understand the problem. then i will give a try to a commit. Thanks for your help

**Comment by lecorguille** [comment]
Maybe it's due to some of my "comestic" changes
Can you try on the W4M production instance?

**Comment by yguitton** [comment]
ok my fault it is OK with a space separated two column files (RI.csv included here) but not with other separators (tab or comma)
[RI.zip](https://github.com/workflow4metabolomics/metaMS/files/359709/RI.zip)

**Comment by yguitton** [comment]
Note I had to change file format in Galaxy as it ws autodetected as gg database format

**Comment by lecorguille** [comment]
Maybe, we can try to allow more format?
Or this file is produced or used by other softs?

**Comment by yguitton** [comment]
Note I had to change file format in Galaxy as it ws autodetected as gg database format
