### ISSUE TITLE
Need a more generic datatype for RI file

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/metaMS#5]
Currently, [RI files](https://github.com/workflow4metabolomics/metaMS/blob/master/galaxy/metaMS/test-data/RI.csv) are detected as gg datatype (galaxy.datatypes.genetics:GenomeGraphs)
This format is not related to RI file but we added it to ease the tool usage.

**Comment by yguitton** [comment]
solved in 2.1.1 (now tsv, txt, csv.. are ok)
